# Generated by Django 3.2.11 on 2022-01-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
